apiVersion: v1alpha1
kind: Role
metadata:
  name: role-template-email-config-view
  labels:
    halo.run/role-template: "true"
  annotations:
    rbac.authorization.halo.run/module: "Email Config"
    rbac.authorization.halo.run/display-name: "Email配置查看"
    rbac.authorization.halo.run/ui-permissions: |
      ["plugin:halo-plugin-email:view"]
rules:
  - apiGroups: [ "" ]
    resources: [ "emailConfigExtensions" ]
    verbs: [ "get", "list" ]
---
apiVersion: v1alpha1
kind: Role
metadata:
  name: role-template-email-config-manage
  labels:
    halo.run/role-template: "true"
  annotations:
    rbac.authorization.halo.run/module: "Email Config"
    rbac.authorization.halo.run/display-name: "Email配置管理"
    rbac.authorization.halo.run/ui-permissions: |
      ["plugin:halo-plugin-email:manage"]
    rbac.authorization.halo.run/dependencies: |
      ["role-template-email-config-view"]
rules:
  - apiGroups: [ "" ]
    resources: [ "emailConfigExtensions" ]
    verbs: [ "create", "patch", "update", "delete", "deletecollection" ]