apiVersion: v1alpha1
kind: Setting
metadata:
  name: mail-settings
spec:
  forms:
    - group: basic
      label: 基本设置
      formSchema:
        - $formkit: checkbox
          help: "测试连接打开地址: http://ip:port/apis/io.mvvm.halo.plugins.email/testConnection"
          label: 启用邮件通知
          name: enable
          value: false
        - $formkit: text
          label: 管理员邮箱
          name: adminMail
          validation: required
        - $formkit: text
          label: FromName
          name: fromName
          validation: required
        - $formkit: text
          help: smtp.qq.com.
          label: Host
          name: host
          validation: required
        - $formkit: text
          help: 465.
          label: Port
          name: port
          validation: required
        - $formkit: text
          help: username.
          label: Username
          name: username
          validation: required
        - $formkit: text
          help: password.
          label: Password
          name: password
          validation: required
        - $formkit: text
          help: smtps, smtp.
          label: Protocol
          name: protocol
          validation: required
        - $formkit: checkbox
          help: enableTls.
          label: Tls
          name: enableTls
          value: false