apiVersion: v1alpha1
kind: Plugin
metadata:
  name: halo-plugin-email
spec:
  enabled: true
  version: 1.1.2
  requires: "2.2.*"
  author:
    name: pannanxu
    website: https://github.com/pannanxu/halo-plugin-email
  logo: https://www.mvvm.io/favico.ico
  settingName: mail-settings
  configMapName: mail-settings
  homepage: https://github.com/pannanxu/halo-plugin-email
  displayName: "邮件通知"
  description: "Halo邮件通知插件"
  license:
    - name: "MIT"